apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: CLUSTERNAME
spec:
  agentVersion: AGENTVERSION # 3.4.2
  repository: docker.io/scylladb/scylla-enterprise
  version: DBVERSION # 2024.2.7
  developerMode: DEVMODE
  automaticOrphanedNodeCleanup: true
  #BAK backups:
  #BAK   - name: s3
  #BAK     location: [s3:scylla-backups]
  #GCS   - name: gcs
  #GCS     location: [gcs:scylla-backups-gke]
  exposeOptions:
    broadcastOptions:
      clients:
        type: PodIP
      nodes:
        type: PodIP
    nodeService:
      type: Headless
  cpuset: true
  sysctls:
    - fs.aio-max-nr=30000000
  #MDC externalSeeds:
  #MDC   - NAMESPACE-rack1-0.NAMESPACE
  datacenter:
    name: DATACENTER
    racks:
      - name:  rack1
        members: 3
        storage:
          capacity: CAPACITY
          storageClassName: scylladb-local-xfs
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: CPULIMIT
            memory: MEMORYLIMIT
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
          tolerations:
            - effect: NoSchedule
              key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
        volumes:
          # - name: tls-certificates
          #   secret:
          #     secretName: scylla-server-certs # Reference the secret containing certificates.
          - name: scylladb-serving-ca
            configMap:
              name: scylla-local-serving-ca
              defaultMode: 420
        #GCS   - name: gcs-service-account
        #GCS     secret:
        #GCS       secretName: gcs-service-account
        volumeMounts:
          # - name: tls-certificates
          #   mountPath: /etc/scylla/certs # Mount path inside the pod.
          - name: scylladb-serving-ca
            readOnly: true
            mountPath: /var/run/configmaps/scylla-operator.scylladb.com/scylladb/serving-ca
        #GCS agentVolumeMounts:
        #GCS   - name: gcs-service-account
        #GCS     mountPath: /etc/scylla-manager-agent/gcs-service-account.json
        #GCS     subPath: gcs-service-account.json
        #GCS     readOnly: true