apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scylladb:controller:manager-controller
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.operator.scylladb.com/aggregate-to-scylla-manager-controller: "true"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scylladb:controller:aggregate-to-manager-controller
  labels:
    rbac.operator.scylladb.com/aggregate-to-scylla-manager-controller: "true"
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - scylla.scylladb.com
  resources:
  - scyllaclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scylla.scylladb.com
  resources:
  - scyllaclusters/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: v1
kind: Namespace
metadata:
  name: scylla-manager

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scylla-manager-controller
  namespace: scylla-manager
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla-manager-controller
      app.kubernetes.io/instance: scylla-manager

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scylla-manager-controller
  namespace: scylla-manager
  labels:
    app.kubernetes.io/name: scylla-manager-controller
    app.kubernetes.io/instance: scylla-manager

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-manager-config
  namespace: scylla-manager
data:
  scylla-manager.yaml: |-
    http: :5080
    logger:
      level: info
    database:
      hosts:
      - scylla-manager-DATACENTER-rack1-0
      # ssl: true
    ssl:
      cert_file: /var/run/configmaps/scylla-manager/client-certs/ca.crt
      user_cert_file: /var/run/secrets/scylla-manager/client-certs/tls.crt
      user_key_file: /var/run/secrets/scylla-manager/client-certs/tls.key
      # cert_file: /var/run/configmaps/scylla-manager/client-ca/ca-bundle.crt
      # user_cert_file: /var/run/secrets/scylla-manager/user-admin/tls.crt
      # user_key_file: /var/run/secrets/scylla-manager/user-admin/tls.key

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: scylla-manager
  name: scylla-manager-to-scylla-pod
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/managed-by: scylla-operator
      app.kubernetes.io/name: scylla
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: scylla-manager

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: scylla-manager
    app.kubernetes.io/instance: scylla-manager
  name: scylla-manager
  namespace: scylla-manager
spec:
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 5080
  - name: metrics
    port: 5090
    protocol: TCP
    targetPort: 5090
  selector:
    app.kubernetes.io/name: scylla-manager
    app.kubernetes.io/instance: scylla-manager

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scylla-manager
  namespace: scylla-manager
  labels:
    app.kubernetes.io/name: scylla-manager
    app.kubernetes.io/instance: scylla-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scylladb:controller:manager-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scylladb:controller:manager-controller
subjects:
- kind: ServiceAccount
  name: scylla-manager-controller
  namespace: scylla-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla-manager-controller
  namespace: scylla-manager
  labels:
    app.kubernetes.io/name: scylla-manager-controller
    app.kubernetes.io/instance: scylla-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla-manager-controller
      app.kubernetes.io/instance: scylla-manager
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scylla-manager-controller
        app.kubernetes.io/instance: scylla-manager
    spec:
      serviceAccountName: scylla-manager-controller
      containers:
      - name: scylla-manager-controller
        image: docker.io/scylladb/scylla-operator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - manager-controller
        - --loglevel=2
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla-manager
  namespace: scylla-manager
  labels:
    app.kubernetes.io/name: scylla-manager
    app.kubernetes.io/instance: scylla-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla-manager
      app.kubernetes.io/instance: scylla-manager
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scylla-manager
        app.kubernetes.io/instance: scylla-manager
    spec:
      serviceAccountName: scylla-manager
      containers:
      - name: scylla-manager
        image: docker.io/scylladb/scylla-manager:3.5.0
        imagePullPolicy: IfNotPresent
        command:
        - /usr/bin/scylla-manager
        args:
        - --config-file=/mnt/etc/scylla-manager/scylla-manager.yaml
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 200Mi
        readinessProbe:
          httpGet:
            path: /api/v1/clusters
            port: 5080
          periodSeconds: 10
          timeoutSeconds: 3

        volumeMounts:
        - name: scylla-manager-config
          mountPath: /mnt/etc/scylla-manager
        - name: scylla-manager-serving-ca
          readOnly: true
          mountPath: /var/run/configmaps/scylla-manager/serving-ca
        - name: scylla-manager-client-ca
          readOnly: true
          mountPath: /var/run/configmaps/scylla-manager/client-ca
        - name: local-serving-certs
          readOnly: true
          mountPath: /var/run/secrets/scylla-manager/serving-certs
        - name: local-user-admin
          readOnly: true
          mountPath: /var/run/secrets/scylla-manager/user-admin
        - name: scylla-manager-client
          readOnly: true
          mountPath: /var/run/secrets/scylla-manager/client-certs

      volumes:
      - name: scylla-manager-config
        configMap:
          name: scylla-manager-config
      - name: scylla-manager-serving-ca
        configMap:
          name: scylla-manager-local-serving-ca
          defaultMode: 420
      - name: scylla-manager-client-ca
        configMap:
          name: scylla-manager-local-client-ca
          defaultMode: 420
      - name: local-serving-certs
        secret:
          secretName: scylla-manager-local-serving-certs
      - name: local-user-admin
        secret:
          secretName: scylla-manager-local-user-admin
      - name: scylla-manager-client 
        secret:
          secretName: scylla-manager-certs
---
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-manager
  namespace: scylla-manager
spec:
  version: DBVERSION
  repository: docker.io/scylladb/scylla-enterprise
  agentVersion: AGENTVERSION
  agentRepository: docker.io/scylladb/scylla-manager-agent
  developerMode: DEVMODE
  cpuset: true
  sysctls:
    - fs.aio-max-nr=30000000
  datacenter:
    name: DATACENTER
    racks:
    - members: MANAGERMEMBERS
      name: rack1
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: scylla.scylladb.com/node-type
                operator: In
                values:
                - scylla
        tolerations:
        - effect: NoSchedule
          key: scylla-operator.scylladb.com/dedicated
          operator: Equal
          value: scyllaclusters
      resources:
        requests:
          cpu: MANAGERDBCPULIMIT
          memory: 100Mi
        limits:
          cpu: MANAGERDBCPULIMIT
          memory: MANAGERDBMEMORYLIMIT
      storage:
        capacity: MANAGERDBCAPACITY 
        storageClassName: STORAGECLASS #scylladb-local-xfs

---
