apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scylla-server-certs
  namespace: scylla
spec:
  secretName: scylla-server-certs # Secret where the certificate will be stored.
  duration: 2160h # Validity period (90 days).
  renewBefore: 360h # Renew before expiry (15 days).
  commonName: scylla
  dnsNames:
    - scylla-dc1-rack1-0.scylla.svc
    - scylla-dc1-rack1-1.scylla.svc
    - scylla-dc1-rack1-2.scylla.svc
    - scylla-dc1-rack1-0.scylla.svc.cluster.local 
    - scylla-dc1-rack1-1.scylla.svc.cluster.local 
    - scylla-dc1-rack1-2.scylla.svc.cluster.local 
  issuerRef:
    name: selfsigned-issuer # Reference to the ClusterIssuer.
    kind: ClusterIssuer
