apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: CLUSTERNAME
spec:
  agentVersion: AGENTVERSION # 3.4.2
  repository: docker.io/scylladb/scylla-enterprise
  version: DBVERSION # 2024.2.7
  developerMode: DEVMODE
  scyllaArgs: "--smp=CPULIMIT" # "--poll-mode"
  repairs:
    - name: weekly-repair
      cron: "0 0 * * 0" # Every Sunday at midnight       
      dc: ["DATACENTER"] # Specify the datacenter to run the repair in
      keyspace: ["*"]  # All keyspaces
      intensity: "1"
      parallel: 0
  exposeOptions:
    broadcastOptions:
      clients:
        type: PodIP
      nodes:
        type: PodIP
    nodeService:
      type: Headless
  # cpuset: true # deprecated
  sysctls:
    - fs.aio-max-nr=30000000
    - fs.nr_open=1073741816
    - fs.file-max=9223372036854775807
  #MDC externalSeeds:
  #MDC   - NAMESPACE-rack1-0.NAMESPACE
  datacenter:
    name: DATACENTER
    racks:
      - name:  rack1
        members: 3
        storage:
          capacity: CAPACITY
          storageClassName: scylladb-local-xfs
        resources:
          requests:
            cpu: CPULIMIT
            memory: MEMORYLIMIT
          limits:
            cpu: CPULIMIT
            memory: MEMORYLIMIT
        agentResources:      # For ScyllaDB Agent container
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
          podAntiAffinity: 
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: scylla
                  matchLabelKeys:
                    - scylla/datacenter
                  topologyKey: kubernetes.io/hostname
          # not supported in ScyllaDB Operator 1.17 
          # podAntiAffinity:
          #   requiredDuringSchedulingIgnoredDuringExecution:
          #     - labelSelector:
          #         matchLabels:
          #           app: scylla
          #         matchLabelKeys:
          #           - scylla/datacenter
          #       topologyKey: kubernetes.io/hostname
          tolerations:
            - effect: NoSchedule
              key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
        volumes:
          # - name: tls-certificates
          #   secret:
          #     secretName: scylla-server-certs # Reference the secret containing certificates.
          # - name: scylladb-serving-ca
          #   configMap:
          #     name: scylla-local-serving-ca
          #     defaultMode: 420
          - name: scylla-server-certs
            secret:
              secretName: scylla-server-certs
              defaultMode: 420
        #GCS   - name: gcs-service-account
        #GCS     secret:
        #GCS       secretName: gcs-service-account
        volumeMounts:
          # - name: tls-certificates
          #   mountPath: /etc/scylla/certs # Mount path inside the pod.
          # - name: scylladb-serving-ca
          #   readOnly: true
          #   mountPath: /var/run/configmaps/scylla-operator.scylladb.com/scylladb/serving-ca
          - name: scylla-server-certs
            readOnly: true
            mountPath: /var/run/secrets/scylla-server-certs/
        #GCS agentVolumeMounts:
        #GCS   - name: gcs-service-account
        #GCS     mountPath: /etc/scylla-manager-agent/gcs-service-account.json
        #GCS     subPath: gcs-service-account.json
        #GCS     readOnly: true