apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaDBMonitoring
metadata:
  name: CLUSTERNAME
spec:
  type: Platform
# [endpointsSelector]
  endpointsSelector:
    matchLabels:
      app.kubernetes.io/name: scylla
      scylla-operator.scylladb.com/scylla-service-type: member
      scylla/cluster: CLUSTERNAME # Replace with your ScyllaCluster name.
# [/endpointsSelector]
# [prometheusMode]
  components:
    prometheus:
      mode: External
# [/prometheusMode]
    grafana:
# [grafanaDatasources]
      datasources:
        - name: prometheus
          type: Prometheus
          url: http://CLUSTERNAME-prometheus.NAMESPACE.svc.cluster.local:9090
          prometheusOptions: {}
# [/grafanaDatasources]
      # set to "Internal" to deploy Prometheus in the cluster
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: scylla.scylladb.com/node-type
                operator: In
                values:
                - NODESELECTOR
