apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: CLUSTERNAME
spec:
  agentVersion: AGENTVERSION # 3.7.0
  repository: docker.io/scylladb/scylla
  version: DBVERSION # 2025.1.5
  developerMode: DEVMODE
  scyllaArgs: "--smp=CPULIMIT" # "--poll-mode"
  #ALT alternator:
  #ALT   port: 8000
  #ALT   writeIsolation: WRITEISOLATION
  repairs:
    - name: weekly-repair
      cron: "0 0 * * 0" # Every Sunday at midnight       
      dc: ["DATACENTER"] # Specify the datacenter to run the repair in
      keyspace: ["*"]  # All keyspaces
      intensity: "1"
      parallel: 0
  exposeOptions:
    broadcastOptions:
      clients:
        type: BROADCASTCLIENTSTYPE
      nodes:
        type: BROADCASTNODESTYPE
    nodeService:
      type: NODESERVICETYPE
  cpuset: true # deprecated
  #v18 sysctls: # deprecated
  #v18   - fs.aio-max-nr=30000000
  #v18   - fs.nr_open=1073741816
  #v18   - fs.file-max=9223372036854775807
  #MDC externalSeeds:
  #MDC  - EXTERNAL-SEED-1
  #MDC  - EXTERNAL-SEED-2
  #MDC  - EXTERNAL-SEED-3
  datacenter:
    name: DATACENTER
    racks:
      - name: rack1
        members: 1
        storage:
          capacity: CAPACITY
          storageClassName: scylladb-local-xfs
        resources:
          requests:
            cpu: CPULIMIT
            memory: MEMORYLIMIT
          limits:
            cpu: CPULIMIT
            memory: MEMORYLIMIT
        agentResources:      # For ScyllaDB Agent container
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - NODESELECTOR
                    #CLOUD - key: topology.kubernetes.io/zone
                    #CLOUD   operator: In
                    #CLOUD   values:
                    #CLOUD   - ZONE1
          podAntiAffinity: 
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: scylla
                  matchLabelKeys:
                    - scylla/datacenter
                  topologyKey: kubernetes.io/hostname
          tolerations:
            - effect: NoSchedule
              key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
        #CTorG volumes:
        #CUSTC   - name: CLUSTERNAME-server-certs
        #CUSTC     secret:
        #CUSTC       secretName: CLUSTERNAME-server-certs
        #CUSTC       defaultMode: 420
        #CERTS   - name: scylladb-serving-ca
        #CERTS     configMap:
        #CERTS       name: CLUSTERNAME-local-serving-ca
        #CERTS       defaultMode: 420
        #GCS   - name: gcs-service-account
        #GCS     secret:
        #GCS       secretName: gcs-service-account
        #CTorG volumeMounts:
        #CUSTC   - name: CLUSTERNAME-server-certs
        #CUSTC     readOnly: true
        #CUSTC     mountPath: /var/run/secrets/scylla-server-certs/
        #CERTS   - name: scylladb-serving-ca
        #CERTS     readOnly: true
        #CERTS     mountPath: /var/run/configmaps/scylla-operator.scylladb.com/scylladb/serving-ca
        #GCS agentVolumeMounts:
        #GCS   - name: gcs-service-account
        #GCS     mountPath: /etc/scylla-manager-agent/gcs-service-account.json
        #GCS     subPath: gcs-service-account.json
        #GCS     readOnly: true
        #GCS     readOnly: true
      - name: rack2
        members: 1
        storage:
          capacity: CAPACITY
          storageClassName: scylladb-local-xfs
        resources:
          requests:
            cpu: CPULIMIT
            memory: MEMORYLIMIT
          limits:
            cpu: CPULIMIT
            memory: MEMORYLIMIT
        agentResources:      # For ScyllaDB Agent container
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - NODESELECTOR
                    #CLOUD - key: topology.kubernetes.io/zone
                    #CLOUD   operator: In
                    #CLOUD   values:
                    #CLOUD   - ZONE2
          podAntiAffinity: 
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: scylla
                  matchLabelKeys:
                    - scylla/datacenter
                  topologyKey: kubernetes.io/hostname
          tolerations:
            - effect: NoSchedule
              key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
        #CTorG volumes:
        #CUSTC   - name: CLUSTERNAME-server-certs
        #CUSTC     secret:
        #CUSTC       secretName: CLUSTERNAME-server-certs
        #CUSTC       defaultMode: 420
        #CERTS   - name: scylladb-serving-ca
        #CERTS     configMap:
        #CERTS       name: CLUSTERNAME-local-serving-ca
        #CERTS       defaultMode: 420
        #GCS   - name: gcs-service-account
        #GCS     secret:
        #GCS       secretName: gcs-service-account
        #CTorG volumeMounts:
        #CUSTC   - name: CLUSTERNAME-server-certs
        #CUSTC     readOnly: true
        #CUSTC     mountPath: /var/run/secrets/scylla-server-certs/
        #CERTS   - name: scylladb-serving-ca
        #CERTS     readOnly: true
        #CERTS     mountPath: /var/run/configmaps/scylla-operator.scylladb.com/scylladb/serving-ca
        #GCS agentVolumeMounts:
        #GCS   - name: gcs-service-account
        #GCS     mountPath: /etc/scylla-manager-agent/gcs-service-account.json
        #GCS     subPath: gcs-service-account.json
        #GCS     readOnly: true

      - name: rack3
        members: 1
        storage:
          capacity: CAPACITY
          storageClassName: scylladb-local-xfs
        resources:
          requests:
            cpu: CPULIMIT
            memory: MEMORYLIMIT
          limits:
            cpu: CPULIMIT
            memory: MEMORYLIMIT
        agentResources:      # For ScyllaDB Agent container
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - NODESELECTOR
                    #CLOUD - key: topology.kubernetes.io/zone
                    #CLOUD   operator: In
                    #CLOUD   values:
                    #CLOUD   - ZONE3
          podAntiAffinity: 
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: scylla
                  matchLabelKeys:
                    - scylla/datacenter
                  topologyKey: kubernetes.io/hostname
          tolerations:
            - effect: NoSchedule
              key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
        #CTorG volumes:
        #CUSTC   - name: CLUSTERNAME-server-certs
        #CUSTC     secret:
        #CUSTC       secretName: CLUSTERNAME-server-certs
        #CUSTC       defaultMode: 420
        #CERTS   - name: scylladb-serving-ca
        #CERTS     configMap:
        #CERTS       name: CLUSTERNAME-local-serving-ca
        #CERTS       defaultMode: 420
        #GCS   - name: gcs-service-account
        #GCS     secret:
        #GCS       secretName: gcs-service-account
        #CTorG volumeMounts:
        #CUSTC   - name: CLUSTERNAME-server-certs
        #CUSTC     readOnly: true
        #CUSTC     mountPath: /var/run/secrets/scylla-server-certs/
        #CERTS   - name: scylladb-serving-ca
        #CERTS     readOnly: true
        #CERTS     mountPath: /var/run/configmaps/scylla-operator.scylladb.com/scylladb/serving-ca
        #GCS agentVolumeMounts:
        #GCS   - name: gcs-service-account
        #GCS     mountPath: /etc/scylla-manager-agent/gcs-service-account.json
        #GCS     subPath: gcs-service-account.json
        #GCS     readOnly: true
