k8sVersion="1.35"
ngVersion="${k8sVersion}"

nodeGroup0size=3
nodeGroup1size=3
nodeGroup2size=1

# arch=x86_64 # 
arch=arm64
region=${awsRegion:-us-west-2}
if [[ "$arch" == "arm64" ]]; then
instance0="i8g.2xlarge" # NVME type dedicafed for Scylla
instance1="m7g.2xlarge" # general operator and other services
instance2="m7g.2xlarge" # application (spark) nodes
else
instance0="i7i.2xlarge" # NVME type dedicated for Scylla
instance1="m5a.2xlarge" # general operator and other services
instance2="r5a.2xlarge" # application (spark) nodes
fi

capacityType="ON_DEMAND" # "SPOT"
ebsSize=100

prefix="tjl-"
vpcId="vpc-412d8839"
sshKey="~/.ssh/aws.pub"
