apiVersion: v1
kind: Pod
metadata:
  name: myapplication
  labels:
    app.kubernetes.io/name: myapplication
spec:
  serviceAccountName: scylla-member
  containers:
    - image: "docker.io/tjlscylladb/apps:3.12-slim"
      name: myapplication
      imagePullPolicy: Always # IfNotPresent
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: /dev/shm
          name: devshm
      resources:
        limits:
          cpu: "4"
          memory: "8Gi"
        requests:
          cpu: "4"
          memory: "8Gi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: scylla.scylladb.com/node-type
            operator: In
            values:
            - scylla-operator
  volumes:
    - name: devshm
      emptyDir:
        medium: Memory
        sizeLimit:   #  64Mi is the default
